#!/bin/sh
#
# makesrcdist - make a source distribution of zipc.
#

if test $# != 1; then
	echo "Usage: ./makesrcdist version"
	exit 1
fi

version=$1

echo Creating tag for release...
git tag -m "Tag $version" v$version
git push origin v$version

echo Creating zipc-$version.tar.gz...
git archive --format tar --prefix=zipc-$version/ HEAD | gzip -v9 >zipc-$version.tar.gz
gpg --detach-sign zipc-$version.tar.gz

